version: '3.9'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=svelte-blog
      - POSTGRES_PASSWORD=localPassword
      - POSTGRES_DB=svelte-blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
